<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForList($filter)
    {
        $qb = $this
            ->createQueryBuilder('post')
            ->select('post')
            ->addOrderBy('post.publishedAt', 'DESC')
        ;

        return $qb->getQuery()->getResult();
    }
}
